### ISSUE TITLE
Single precision

### ISSUE THREAD

**Issue by ivobatkovic** [giaf/hpipm#147]
Hi Gianluca, 

I've used HPMPC and HPIPM in my research and would like to say that I truly appreciate the great work you are doing!

I'm interested in the use of the single precision version of HPIPM, but I couldn't find any examples in the repo. I decided to try it out myself, so I forked the repo and pushed a commit here: `https://github.com/giaf/hpipm/commit/87e68051b07d3e1f7895c3d1c3d0c7f58a95cb43`

Running this single precision version, however, yields NaN values and I'm not really sure if it is due mistakes/misunderstandings from my end, or if it is the solver.  I've played around with the solver tunings that are set in one of the files but nothing helps. I've just noticed that `mu` in the IPM loop explodes after a few iterations.

Questions:
1. Is there a bug in the single precision version of HPIPM or am I using it wrong?
2. Are there any speed benefits to using single precision compared to the double precision?

Best regards,
Ivo

**Comment by giaf** [comment]
Hi Ivo,

thanks for the interest in HPIPM and the encouraging words :)

I have also implemented the single precision because it comes kind of for free, the code is implemented in generic x_... files and then macros are used to compile the same source to double precision d_... and single precision s_... files.
So the code is virtually identical between double and single precision.

The use of single precision IPM methods is a bit limited in practice, that's also why there are not many examples and tests.
The point is that internal computations in IPM would get by their nature very ill-conditioned toward the last iterations, as the iterates approach the solution.
So they can be successfully used only for moderate accuracy solutions in case of well conditioned problems.

The possible speed advantage depends on the problem and the machine.
On high performance architectures with vector FP units, typically you can cast twice as many floats per vector register as doubles, so you can expect a 2x throughput in these computations and thus in matrix operations with large enough matrices (say, at least several tens of size).
In practice the speedup of the overall solver is lower as other operations can't be vectorized.

On low power machines, it may happen that single precision FP implementation is rather fast (e.g. present in hardware and pipelined), while double precision FP implementation is slow or non-native (e.g. provided by the compiler using libraries). In these cases the speed up can be important, also for small sized problems.

Finally the single precision version uses less storage for data, that can be important in some embedded applications.

**Comment by ivobatkovic** [comment]
Hi again,

Thank you for the fast reply and for giving a detailed summary for the single precision pros/cons. However, I think I stumbled upon something that might be of interest.

The code I refer to above consists of a double integrator and I noticed the following:
1. Building blasfeo for an automatic target (in my case `X64_INTEL_HASWELL`) both the double and single precision examples work.
2. Building blasfeo for a generic target, the single precision example yields NaN's, while the double precision example solves successfully.

I used a debugger to step through both examples until I found a discrepancy between two. I saw that in file `blasfeo_hp_pm/s_lapack_lib4.c` the function `blasfeo_hp_ssyrk_spotrf_ln_mn` was different than the corresponding double version. I tried patching it by:
1. Copying the `blasfeo_hp_dsyrk_dpotrf_ln_mn` function and just replacing all the double calls to single calls. Doing so gives me a converged solution for the single precision example. [Code found here](https://github.com/ivobatkovic/blasfeo/commit/c0076b5e55d3ca9b089fc5af908d560833f006cd)
2. I noticed that it was only some variables that differed in the function calls, e.g., double used `k` while single used `j`, so I tried to make it as similar with the fewest changes possible. This also seems to make the single precision example to converge. [Code found here](https://github.com/ivobatkovic/blasfeo/commit/dcf800938e42e9aa0ff4f6f5965323aa2b034dcc)

Is there perhaps something that was forgotten to be updated in the single precision version of blasfeo or is this intended? I'm curious whether my changes makes sense, or if it just is a coincidence that this somehow fixes the NaN values in the HPIPM example.

**Comment by giaf** [comment]
Yes it looks like some old buggy code has been in there for a long time unnoticed until now :p thanks for spotting!
This should fix the issue https://github.com/giaf/blasfeo/commit/af98e7fb7ae31178bfb3ebdc3c8a4bd8e37d5141
That's basically your point 2. plus a few other fixes, also to another routine.

About point 1. it's a bit more complicated than that, e.g. the kernels `kernel_sgemm_strsm_nt_rl_inv_12x4_lib4` don't exist for haswell, and in general that source is not even compiled for haswell, since in single precision haswell has a panel size of 8, so the `s_lapack_lib8.c` would be the corresponding source.

Can you check if this makes the job for you?

**Comment by ivobatkovic** [comment]
Hi, sorry for the delayed response.

The commit above does indeed fix the NaN values! Thank you very much for the quick update!

However, I'm still a bit surprised that the single precision is much more sensitive than the double precision in very simple OCP problem formulations. I really have to tune down the tolerances a lot in order to get the QP to converge consistently. I guess it is due to the reasons you mentioned above.

Again, thank you for the quick response. I'll mark this issue as solved/closed.
