### ISSUE TITLE
[ct-v2] fail to compile

### ISSUE THREAD

**Issue by KahnShi** [giaf/hpipm#23]
Hi all,

When I tried to compile the tag ct-v2 on my Ubuntu 16.04 64-bits pc, it fails as the following file.

[hpipm-ct-v2-error.txt](https://github.com/giaf/hpipm/files/1756052/hpipm-ct-v2-error.txt)

Could anyone give me any hint?
Thank you in advance!

Best,
Kahn

**Comment by tmmsartor** [comment]
This may be caused by a wrong version of BLASFEO installed in `/opt/`,
have you run `make install` from BLASFEO repository after checking out the `ct-v2` branch?
NB:  BLASFEO `ct-v2` branch (it was a tag) have been updated recently.

With both HPIPM and BLASFEO checkout to `ct-v2` on SANDY_BRIDGE I cannot replicate the problem.
Which CPU architecture are you using on your machine?

**Comment by KahnShi** [comment]
Hi @tmmsartor 

I think it is because the wrong version of BLASFEO like you said.
Now it could work smoothly with the BLASFEO `ct-v2` branch.

Again thank you so much for your help!
Best,
Kahn
