### ISSUE TITLE
Optimization reaches minimal step length

### ISSUE THREAD

**Issue by dawgster** [giaf/hpipm#56]
Hello!
I have a question regarding solving an OCP. I have setup the problem, however the solver returns code 2 which indicates reaching the minimal step length. What exactly does this mean and does this indicate that my problem does not have a solution? Do you have suggestion on a workflow to debug such an issue? 

Regards

**Comment by giaf** [comment]
Minimum step length reached may mean that the problem is unfeasible, or that the problem is feasible but somehow "hard" and the solver could not converge.

The Mehrotra's type interior point algorithm implemented does not give a certificate of infeasibility, so you can try to solve it with another solver (with e.g. an active set) to check which is the case.

Alternatively, you can check the `stat` field and the residuals at each iteration. If the problem is feasible you typically see that the solver is converging until at some point it starts diverging again: the final iterations of an interior point require the solution of ill-conditioned linear systems, and at that point the accuracy of the double precision computations may not enough. Switching to the `robust` mode (https://github.com/giaf/hpipm/blob/master/examples/c/example_d_ocp_qp.c#L137) may help, or the exit tolerances (https://github.com/giaf/hpipm/blob/master/examples/c/example_d_ocp_qp.c#L142 and following) should be reduced.
