### ISSUE TITLE
Fails with BUILD_SHARED_LIBS=ON

### ISSUE THREAD

**Issue by yurivict** [giaf/hpipm#71]
Fails to build the shared library:
```
ninja: error: '/opt/blasfeo/lib/libblasfeo.a', needed by 'libhpipm.so', missing and no known rule to make it
```

**Comment by giaf** [comment]
`ninja` is not used in HPIPM. So I guess this issue issue should regard acados instead.
@zanellia does it sound familiar?

**Comment by yurivict** [comment]
ninja is just a build method that cmake can use to build projects, alternative to GNU make.

**Comment by giaf** [comment]
So are you using HPIPM stand alone, and not as part of acados https://github.com/acados/acados ? (there ninja is used in part of the project)

**Comment by giaf** [comment]
Anyway, your issue is a bit scarce of details about what you are doing. So let me explain the workflow.

HPIPM uses BLASFEO https://github.com/giaf/blasfeo as a dependency. So first you need to compile (in your case the shared library) and install (by default in `/opt/blasfeo`) BLASFEO.

At that point you can compile HPIPM, setting properly `BLASFEO_PATH` https://github.com/giaf/hpipm/blob/stable/CMakeLists.txt#L61 to match your chosen installation location and `HPIPM_BLASFEO_LIB` to either static or dynamic depending on your needs.

Did you follow these steps?

**Comment by yurivict** [comment]
Thanks for your explanation. I will open another issue.
