### ISSUE TITLE
example build fails on tag 0.1.2

### ISSUE THREAD

**Issue by markusgft** [giaf/hpipm#84]
Dear @giaf,
a control-toolbox user just reported to me the following bug on hpipm tag 0.1.2: building the examples fails with
```
Parsing Makefile.rule
cp libhpipm.a ./examples/c/libhpipm.a
( cd examples/c; make obj )
make[1]: Entering directory '/tmp/hpipm/examples/c'
Parsing Makefile.rule
make[1]: *** No rule to make target '../matlab_octave/ocp_qp_data.o', needed by 'obj'.  Stop.
make[1]: Leaving directory '/tmp/hpipm/examples/c'
Makefile:239: recipe for target 'examples' failed
make: *** [examples] Error 2
```

**Comment by giaf** [comment]
Thanks for the feedback.

The fact that in the C examples, the QP data is taken form some data files.
That missing file would be created if some matlab/octave examples are run before.
In the makefile, it was mistakenly selected that data file instead of a default one, in the current main is now fixed like this
https://github.com/giaf/hpipm/blob/master/examples/c/Makefile#L44

**Comment by markusgft** [comment]
Thanks for clarifying. I will forward the release branch to using the current versions of hpipm/blasfeo to avoid the error.
